name: 5.0.0+trunk+serial

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: caml/opam:ubuntu-20.04-ocaml-4.12
    continue-on-error: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: 5.0.0+trunk+serial
        run: |
          sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip autoconf jo
          pip3 install intervaltree
          sudo chown -R opam .
          opam update
          opam install dune.2.9.0
          eval $(opam env)
          export ITER=1
          export OPAM_DISABLE_SANDBOXING=true
          TAG='"run_in_ci"' make run_config_filtered.json
          USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/5.0.0+trunk.bench
          ls _results
          cat _results/*
